### ISSUE TITLE
face a problem when training,please help me 

### ISSUE THREAD

**Issue by csuquan** [tureckova/ISLES2018#2]
`[INFO] model compiled
Epoch 1/250

Epoch 00001: LearningRateScheduler setting learning rate to 0.005.
Traceback (most recent call last):
  File "train.py", line 146, in <module>
    , validation_steps=np.ceil(float(len(testX)) / config["batch_size"])
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2721, in __call__
    return self._legacy_call(inputs)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2693, in _legacy_call
    **self.session_kwargs)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 968, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'NoneType'
`

I dont know how to solve this.
sad

**Comment by tureckova** [comment]
Hi, sorry for the late reply. Have you already solved the problem?
It seems there is some trouble with the function fit_generator. I would look at the generator function and check the input data format, size and dimensions. But can't really help you without the context...

**Comment by crazyzhaozhaojun** [comment]
> Hi, sorry for the late reply. Have you already solved the problem?
> It seems there is some trouble with the function fit_generator. I would look at the generator function and check the input data format, size and dimensions. But can't really help you without the context...

hi,can you give me the link of your paper?

**Comment by tureckova** [comment]
Hi @crazyzhaozhaojun the paper is still under the publication process, but I guess it will be out during January. Hold on a while, please.

**Comment by crazyzhaozhaojun** [comment]
Thanks for your reply so much!  If the paper is published successfully, can you make it public on Github or send me an email? Thank you!   1780634287@qq.com

**Comment by HannibalXing** [comment]
> `[INFO] model compiled
> Epoch 1/250
> 
> Epoch 00001: LearningRateScheduler setting learning rate to 0.005.
> Traceback (most recent call last):
> File "train.py", line 146, in 
> , validation_steps=np.ceil(float(len(testX)) / config["batch_size"])
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
> return func(*args, **kwargs)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
> initial_epoch=initial_epoch)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
> class_weight=class_weight)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
> outputs = self.train_function(ins)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2721, in **call**
> return self._legacy_call(inputs)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2693, in _legacy_call
> **self.session_kwargs)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
> run_metadata_ptr)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 968, in _run
> np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
> File "/home/cb201/anaconda3/envs/quanquan/lib/python3.6/site-packages/numpy/core/numeric.py", line 501, in asarray
> return array(a, dtype, copy=False, order=order)
> TypeError: float() argument must be a string or a number, not 'NoneType'
> `
> 
> I dont know how to solve this.
> sad

I think I have the same issue for the script. Any update or reason? looks like something wrong with the fit_generator. I am not sure yet.
